version: '3.9'
services:
  #  app:
  #    image: boilerplate:latest
  #    container_name: boilerplate-app
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #      target: development
  #    ports:
  #      - '3000:3000'
  #    depends_on:
  #      - redis
  #      - db
  #    volumes:
  #      - type: bind
  #        source: ./src
  #        target: /usr/src/app/src
  #    entrypoint: ["pnpm", "run", "start:dev"]
  db:
    image: postgres
    container_name: boilerplate-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    container_name: boilerplate-redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
volumes:
  postgres-data:
    external: true
